# Generated by Django 3.2.8 on 2021-10-18 02:01

from django.db import migrations, models
import django.db.models.deletion
import psqlextra.manager.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.TextField()),
                ('key', models.TextField()),
            ],
            options={
                'db_table': 'Account',
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject', models.TextField()),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('SE', 'Sent'), ('FA', 'Failed')], default='PE', max_length=2)),
                ('receivers', models.TextField()),
                ('body', models.TextField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.account')),
            ],
            options={
                'db_table': 'Email',
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
