# Generated by Django 3.2.8 on 2021-10-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='tittle',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='email',
            name='sender_name',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
    ]
